# Site settings
title: Delphine's blog
email: cndanfeng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hahahahahaha!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Delphine
github_username:  Delphine

# Build settings
markdown: kramdown
